config/routes.rb
Rails.application.routes.draw do

  resources :order_details
  resources :notifications
  resources :orders do
    resources :items
  end
  get 'follows/index'

  get 'home/index'
  get 'all' => 'users#all'
  get '/complete/:id', to: 'orders#complete'
  get '/join/:id', to: 'order_details#join'
  # match 'add', to: 'order_details#add', via: [:post]
  # post 'invite' => 'users#invite'
  # match 'invites', to: 'users#invite', via: [:post]

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  mount ActionCable.server => '/cable'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users do
     resources :groups
  end
  resources :groups

  resources :groups do
    member do
      post :new_member
      delete :delete_member
     # post '/newfollow', to: 'users#newfollow'
    end
 end

  resources :follows
 match 'users/newfollow' => 'users#newfollow', :via => :post
  resources :users do
     member do
       get :follow
       get :unfollow
      # post '/newfollow', to: 'users#newfollow'
     end
  end
 #root 'users#index'
 root  'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :order
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @order=Order.find(params[:order_id])


    @items = @order.items.all
    @item = @order.items.new
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @order=Order.find(params[:order_id])
    @item = @order.items.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @order=Order.find(params[:order_id])
    @item =@order.items.new(item_params)
    @item.order_id=@order.id
    @item.user_id = current_user.id
    respond_to do |format|
      if @item.save
        ##################################### Update Join ################################################
        @order.joined += 1
        @order.save
        ########################
        @order_detail = @order.order_details.where(user_id: @item.user_id)
        puts "kkk"<<@order_detail.inspect
        if @order_detail.empty?
          format.html { redirect_to order_path(@order), notice: 'You should be one of Invited Friends' }
        else
          @order_detail[0].joined = 1
          @order_detail[0].save
          puts "joined "<<@order_detail.inspect
        end
        ###########################################End[Update Join]#######################################
        format.html { redirect_to order_path(@order), notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }

        Pusher.trigger('items-channel', 'last-items', {
            message: @item,
            username: current_user.name,
            ordermeal: @order.meal
        });
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    @item.order_id=@order.id
    @item.user_id = current_user.id
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to order_path(@order), notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to order_items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @order=Order.find(params[:order_id])
      @item = @order.items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :user_id, :order_id, :amount, :price, :comment)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for([@order,@item]) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="border-form-div">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <!-- <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div> -->

  <!-- <div class="field">
    <%= f.label :order_id %>
    <%= f.text_field :order_id %>
  </div> -->

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', order_item_path(@order), :class => 'btn btn-sm btn-success' %> |
<%= link_to 'Back', order_items_path(@order), :class => 'btn btn-sm btn-success' %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<!------------------------------------------------- Modal for friends invited ------------------------------------------->
<button type="button" style="margin-left: 5px" class="btn btn-primary pull-right" data-toggle="modal" data-target="#exampleModal1" data-whatever="@mdo">Friends Invited</button>
<div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title" id="exampleModalLabel">Friends Invited</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% @friends_Invited.each do |i| %>
            <p class="card-text" style="border: 2px double green;text-align: center;font-size: 25px;width: 25%;padding: 5px;float: left">
              <span class="text-muted">UserName</span><br><br>
              <%= i %>
            </p>
        <% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>
<!------------------------------------------------End[ Modal for friends invited ]------------------------------------------->

<!------------------------------------------------- Modal for friends Joined ------------------------------------------->
<button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#exampleModal2" data-whatever="@mdo">Friends Joined</button>
<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title" id="exampleModalLabel">Friends Joined</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% @friends_Joined.each do |i| %>
            <p class="card-text" style="border: 2px double green;text-align: center;font-size: 25px;width: 25%;padding: 5px;float: left">
              <span class="text-muted">UserName</span><br><br>
              <%= i %>
            </p>
        <% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>
<!------------------------------------------------End[ Modal for friends Joined ]------------------------------------------->

<h1>Order Details</h1>
<div id="all-items" style="float:right">

<table class="table table-striped" >
  <thead>
    <tr>
      <th>Item</th>
      <th>Person</th>
      <th>Order</th>
      <th>Amount</th>
      <th>Price</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="bodyItemsTable">
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.user.name %></td>
        <td><%= item.order.meal %></td>
        <td><%= item.amount %></td>
        <td><%= item.price %></td>
        <td><%= item.comment %></td>
        <td><%= link_to 'Show', order_item_path(@order,item), :class => 'btn btn-sm btn-success' %></td>
        <td><%= link_to 'Edit', edit_order_item_path(@order,item), :class => 'btn btn-sm btn-warning' %></td>
        <td><%= link_to 'Destroy', order_item_path(@order,item), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-sm btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>



<div style="float:left;">
  <%= form_for([@order,@order.items.build]) do |f| %>
<div class="border-form-div">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <!-- <div class="field">
      <%= f.label :user_id %>
      <%= f.text_field :user_id %>
    </div> -->

    <div class="field">
      <%= f.label :amount %>
      <%= f.number_field :amount %>
    </div>

    <div class="field">
      <%= f.label :price %>
      <%= f.number_field :price %>
    </div>

    <div class="field">
      <%= f.label :comment %>
      <%= f.text_area :comment %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
</div>
  <% end %>


</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', order_items_path(@order) , :class => 'btn btn-sm btn-success'%>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @item.user.name %>
</p>

<p>
  <strong>Order:</strong>
  <%= @item.order.meal %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @item.amount %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @item.comment %>
</p>

<%= link_to 'Edit', edit_order_item_path(@order,@item), :class => 'btn btn-sm btn-warning' %> |
<%= link_to 'Back', order_items_path(@order), :class => 'btn btn-sm btn-success' %>